name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"

      - run: npm ci

      - run: npm run build

      - run: npm test

      - run: npm publish
